name: publish

on:
  push:
    tags: [ v* ]
  workflow_dispatch:

jobs:
  build-publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup dotNET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.x
          9.x
    - name: Restore
      run: |
        dotnet restore Pek.Mail/Pek.Mail.csproj
        dotnet restore Pek.Mail.Extensions/Pek.Mail.Extensions.csproj
    - name: Build
      run: |
        dotnet pack --no-restore --version-suffix $(date "+%Y.%m%d") -c Release -o out Pek.Mail/Pek.Mail.csproj
        dotnet pack --no-restore --version-suffix $(date "+%Y.%m%d") -c Release -o out Pek.Mail.Extensions/Pek.Mail.Extensions.csproj
    - name: Publish
      run: |
        dotnet nuget push ./out/*.nupkg --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.nugetKey }}
        dotnet nuget push ./out/*.nupkg --skip-duplicate --source https://nuget.deng-hao.com/v3/index.json --api-key ${{ secrets.mynugetKey }}
